# Generated by Django 5.1.4 on 2025-01-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Listings', '0004_remove_joblisting_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='empty',
            field=models.IntegerField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
