# Generated by Django 5.1.4 on 2025-01-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Listings', '0005_joblisting_empty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='empty',
            field=models.IntegerField(),
        ),
    ]
