# Generated by Django 5.1.4 on 2025-02-02 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Listings', '0006_alter_joblisting_empty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='empty',
        ),
    ]
